name: Run

on:
  workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert deb to IPA
      run: |
        # Utiliser le fichier .deb local
        cp pour\ lucas.deb ${{ github.workspace }}/app.deb
        
        # Extraire le fichier .deb
        dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/app

        # Lister le contenu extrait pour vérifier la structure
        echo "Contenu extrait:"
        ls -R ${{ github.workspace }}/app

        # Créer le dossier Payload
        mkdir -p ${{ github.workspace }}/ipa/Payload
        
        # Adapter le chemin d'accès en fonction de la structure (ajustez ce chemin après vérification)
        cp -R ${{ github.workspace }}/app/* ${{ github.workspace }}/ipa/Payload
        
        # Créer le fichier .ipa
        cd ${{ github.workspace }}/ipa
        zip -r ${{ github.workspace }}/App.ipa .

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: App
        path: ${{ github.workspace }}/App.ipa
